#!/usr/bin/env bash
# Cryo Ambient bar mood daemon.

set -u

ACCENT_FILE="$HOME/.config/waybar/accent.css.live"
ENABLE_FLAG="$HOME/.config/cryo/bar-mood.enabled"
INTERVAL=300 # 5 minutes

# Off by default — only run if the user has explicitly enabled the
# feature via `bar-mood on`. Hyprland's exec-once always spawns this
# script; it's a no-op when the flag file is absent.
[ -f "$ENABLE_FLAG" ] || exit 0

# Stop tables — index aligned across all three arrays.
STOPS_H=(0 6 12 18 22 24)
STOPS_T=(5b75d2 5eead4 7af0db 6cd5c0 6395c4 5b75d2)
STOPS_I=(5e6cc8 818cf8 919cf8 818cf8 6e7fdf 5e6cc8)

# Interpolate one channel between two hex bytes given a 0..1 t.
# POSIX awk doesn't parse `0x..` literals, so convert in bash first.
chan_interp() {
  local d1=$((16#$1)) d2=$((16#$2)) t="$3"
  awk -v d1="$d1" -v d2="$d2" -v t="$t" \
    'BEGIN{ printf "%02x", int( d1 + (d2 - d1) * t + 0.5 ) }'
}

# Interpolate a full hex colour between two stops.
hex_interp() {
  local c1="$1" c2="$2" t="$3"
  local rr gg bb
  rr=$(chan_interp "${c1:0:2}" "${c2:0:2}" "$t")
  gg=$(chan_interp "${c1:2:2}" "${c2:2:2}" "$t")
  bb=$(chan_interp "${c1:4:2}" "${c2:4:2}" "$t")
  printf '%s%s%s' "$rr" "$gg" "$bb"
}

# Given decimal hour, return "teal indigo".
colours_for_hour() {
  local h="$1"
  local n=${#STOPS_H[@]}
  local i
  for ((i = 0; i < n - 1; i++)); do
    local h1=${STOPS_H[i]} h2=${STOPS_H[i + 1]}
    if awk -v h="$h" -v h1="$h1" -v h2="$h2" 'BEGIN{exit !(h>=h1 && h<h2)}'; then
      local t
      t=$(awk -v h="$h" -v h1="$h1" -v h2="$h2" 'BEGIN{print (h - h1) / (h2 - h1)}')
      local teal indigo
      teal=$(hex_interp "${STOPS_T[i]}" "${STOPS_T[i + 1]}" "$t")
      indigo=$(hex_interp "${STOPS_I[i]}" "${STOPS_I[i + 1]}" "$t")
      printf '%s %s\n' "$teal" "$indigo"
      return
    fi
  done
  # Edge case (h >= 24): wrap
  printf '%s %s\n' "${STOPS_T[0]}" "${STOPS_I[0]}"
}

write_accent() {
  local hour now teal indigo
  now=$(date +%s)
  hour=$(awk -v n="$now" 'BEGIN{print (n % 86400) / 3600}')
  read -r teal indigo < <(colours_for_hour "$hour")

  local tmp
  tmp=$(mktemp -p "$(dirname "$ACCENT_FILE")" .accent.XXXX)
  {
    echo "/* Cryo — accent.css.live (auto-generated by bar-mood-daemon)"
    echo " * Regenerated every $INTERVAL seconds; do not edit by hand. */"
    echo "@define-color teal   #${teal};"
    echo "@define-color indigo #${indigo};"
  } >"$tmp"
  mv "$tmp" "$ACCENT_FILE"
}

reload_waybar() {
  # SIGUSR2 = reload style; safe if waybar isn't running yet.
  pkill -SIGUSR2 -x waybar 2>/dev/null || true
}

while true; do
  write_accent
  reload_waybar
  sleep "$INTERVAL"
done
