-- Cryo — Hyprland configuration
-- See https://wiki.hypr.land/Configuring/Start/
-- Since Hyprland 0.55 hyprlang is deprecated in favour of Lua.

local vars = require("vars")

-- Nvidia specific tweaks.
-- Generated by install.sh, so it is absent on a fresh clone. A missing file
-- must not abort the rest of the config, hence the pcall.
local ok, err = pcall(require, "nvidia")
if not ok then
    print("[cryo] nvidia.lua not loaded: " .. tostring(err))
end

hl.env("GTK_THEME", "Tokyonight-Dark")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("XCURSOR_THEME", "Adwaita")

-- Autostart. The hyprlang equivalent of `exec-once`.
-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/waybar/launch.sh")
    hl.exec_cmd("quickshell")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("dunst")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text  --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("~/.config/quickshell/htb-vpn-daemon.sh")
    hl.exec_cmd("kitty --class=scratchpad-kitty", { workspace = "special:scratchpad silent" })
    hl.exec_cmd("~/.config/waybar/bar-mood-daemon.sh")
    hl.exec_cmd("~/.local/bin/wallpaper-restore")
    hl.exec_cmd("fcitx5 -d")
end)

require("binds")

hl.layer_rule({ match = { namespace = "^(waybar)$" },        blur = true, ignore_alpha = 0.2 })
hl.layer_rule({ match = { namespace = "^(quickshell)$" },    blur = true, ignore_alpha = 0.2 })
hl.layer_rule({ match = { namespace = "^(notifications)$" }, blur = true, ignore_alpha = 0.2 }) -- dunst
hl.layer_rule({ match = { namespace = "^(wofi)$" },          blur = true, ignore_alpha = 0.2 })

hl.window_rule({ match = { class = "^(firefox)$" }, opacity = "1.0 override 1.0 override" })
hl.window_rule({ match = { class = "^(mpv)$" },     opacity = "1.0 override 1.0 override" })
hl.window_rule({ match = { class = "^(vlc)$" },     opacity = "1.0 override 1.0 override" })

hl.config({
    general = {
        gaps_in     = 2,
        gaps_out    = 4,
        border_size = 2,
        col = {
            active_border   = { colors = { "rgba(5eead4cc)", "rgba(818cf8cc)" }, angle = 45 },
            inactive_border = "rgba(41455988)",
        },
        layout        = "dwindle",
        allow_tearing = true,
    },

    decoration = {
        rounding           = 4,
        active_opacity     = 0.95,
        inactive_opacity   = 0.88,
        fullscreen_opacity = 1.0,

        blur = {
            enabled           = true,
            size              = 8,
            passes            = 3,
            new_optimizations = true,
            ignore_opacity    = true,
            xray              = true,
        },

        shadow = {
            enabled = false,
        },
    },

    animations = {
        enabled = true,
    },
})

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("overshoot",   { type = "bezier", points = { { 0.05, 0.9 },  { 0.1, 1.1 } } })
hl.curve("softSpring",  { type = "bezier", points = { { 0.34, 1.56 }, { 0.64, 1.0 } } })
hl.curve("expoOut",     { type = "bezier", points = { { 0.16, 1.0 },  { 0.3, 1.0 } } })
hl.curve("smoothInOut", { type = "bezier", points = { { 0.45, 0.05 }, { 0.55, 0.95 } } })

hl.animation({ leaf = "windowsIn",        enabled = true,  speed = 2, bezier = "overshoot",   style = "popin 85%" })
hl.animation({ leaf = "windowsOut",       enabled = true,  speed = 1, bezier = "expoOut",     style = "popin 90%" })
hl.animation({ leaf = "windowsMove",      enabled = true,  speed = 2, bezier = "softSpring" })

hl.animation({ leaf = "fade",             enabled = true,  speed = 2, bezier = "expoOut" })
hl.animation({ leaf = "fadeShadow",       enabled = true,  speed = 2, bezier = "expoOut" })
hl.animation({ leaf = "fadeDim",          enabled = true,  speed = 3, bezier = "smoothInOut" })

hl.animation({ leaf = "border",           enabled = true,  speed = 3, bezier = "smoothInOut" })

hl.animation({ leaf = "workspaces",       enabled = false })
hl.animation({ leaf = "specialWorkspace", enabled = true,  speed = 2, bezier = "overshoot",   style = "slidefadevert -50%" })

hl.animation({ leaf = "layers",           enabled = true,  speed = 1, bezier = "expoOut",     style = "fade" })
hl.animation({ leaf = "layersIn",         enabled = true,  speed = 1, bezier = "expoOut",     style = "fade" })
hl.animation({ leaf = "layersOut",        enabled = true,  speed = 1, bezier = "expoOut",     style = "fade" })

-- Monitor setup
require("monitors")

-- Workspaces setup
require("workspaces")

hl.config({
    misc = {
        disable_hyprland_logo        = true,
        disable_splash_rendering     = true,
        animate_manual_resizes       = true,
        animate_mouse_windowdragging = true,
        vrr                          = 2,
        focus_on_activate            = true,
    },

    dwindle = {
        preserve_split = true,
        smart_resizing = true,
    },

    input = {
        kb_layout     = "us",
        sensitivity   = 0,
        accel_profile = "flat",
        follow_mouse  = 1,
    },
})

hl.workspace_rule({
    workspace        = "special:scratchpad",
    on_created_empty = "kitty --class=scratchpad-kitty",
    gaps_in          = 14,
    gaps_out         = 24,
})
