unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm-kitty:Tc"

set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 10
set -g focus-events on

unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind r source-file ~/.tmux.conf \; display "reloaded"

set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#292c3c,fg=#c6d0f5"
set -g status-interval 5

set -g status-left-length 30
set -g status-left "#[bg=#5eead4,fg=#303446,bold] #S #[bg=#292c3c,fg=#5eead4]#[default] "

set -g status-right-length 60
set -g status-right "#[fg=#a5adce]#h #[fg=#414559]│ #[fg=#5eead4]%H:%M #[fg=#414559]│ #[fg=#818cf8]%d %b "

setw -g window-status-format "#[fg=#a5adce] #I:#W "
setw -g window-status-current-format "#[bg=#414559,fg=#5eead4,bold] #I:#W "
setw -g window-status-activity-style "fg=#f87171"

set -g pane-border-style "fg=#414559"
set -g pane-active-border-style "fg=#5eead4"

set -g message-style "bg=#414559,fg=#5eead4"
set -g message-command-style "bg=#414559,fg=#818cf8"

setw -g mode-style "bg=#5eead4,fg=#303446"
