# Font
font_family                 JetBrainsMono Nerd Font
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
font_size                   12.0
disable_ligatures           never
modify_font                 cell_height 110%

# Surfaces
background                  #1a1b26
foreground                  #c0caf5
cursor                      #5eead4
cursor_text_color           #1a1b26
cursor_shape                block

# I really dislike blink so no thank you
cursor_blink_interval       0
cursor_stop_blinking_after  0

# Selection
selection_background        #292e42
selection_foreground        #c0caf5

# Window chrome
window_padding_width        12
hide_window_decorations     yes
confirm_os_window_close     0
window_border_width         0
draw_minimal_borders        yes
inactive_text_alpha         0.9

# Transparency
background_opacity          0.95
dynamic_background_opacity  yes

# Tab bar
tab_bar_min_tabs            2
tab_bar_edge                top
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          "{index}: {title}"
active_tab_foreground       #1a1b26
active_tab_background       #5eead4
active_tab_font_style       bold
inactive_tab_foreground     #a5adce
inactive_tab_background     #292c3c


# URLs
url_color                   #818cf8
url_style                   single
underline_hyperlinks        hover
detect_urls                 yes


# Mouse
mouse_hide_wait             2.5
copy_on_select              clipboard
strip_trailing_spaces       smart
focus_follows_mouse         no

## ANSI palette

# Black
color0                      #15161e
color8                      #414868
# Red
color1                      #f87171
color9                      #f87171
# Green
color2                      #5eead4
color10                     #5eead4
# Yellow
color3                      #818cf8
color11                     #818cf8
# Blue
color4                      #818cf8
color12                     #818cf8
# Magenta
color5                      #818cf8
color13                     #818cf8
# Cyan
color6                      #5eead4
color14                     #5eead4
# White
color7                      #c6d0f5
color15                     #c6d0f5


# Misc
enable_audio_bell           no
visual_bell_duration        0
scrollback_lines            10000
scrollback_paper_history_size 2048
shell_integration           enabled
allow_remote_control        yes

